import jsPDF from "jspdf";

interface NoteData {
  title: string;
  subject: string;
  topicName: string;
  content: string;
  summary: string | null;
  keyFormulas: string[];
  commonMistakes: string[];
  examTips: string[];
  questionCount: number;
  difficulty: string;
}

// ─── Brand colors ───
const COLORS = {
  green: [34, 197, 94] as [number, number, number],
  darkGreen: [10, 31, 10] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
  textPrimary: [17, 24, 39] as [number, number, number],
  textSecondary: [75, 85, 99] as [number, number, number],
  textMuted: [156, 163, 175] as [number, number, number],
  border: [229, 231, 235] as [number, number, number],
  bgLight: [249, 250, 251] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  greenBg: [240, 253, 244] as [number, number, number],
  redBg: [254, 242, 242] as [number, number, number],
  amberBg: [255, 251, 235] as [number, number, number],
};

const PAGE_W = 210; // A4 mm
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - 2 * MARGIN;

function cleanMath(text: string): string {
  if (!text) return "";
  // Display math
  text = text.replace(/\$\$([\s\S]+?)\$\$/g, (_, m) => cleanLatex(m));
  // Inline math
  text = text.replace(/\$(.+?)\$/g, (_, m) => cleanLatex(m));
  // Markdown bold/italic
  text = text.replace(/\*\*(.+?)\*\*/g, "$1");
  text = text.replace(/\*(.+?)\*/g, "$1");
  return text;
}

function cleanLatex(tex: string): string {
  let t = tex.trim();
  t = t.replace(/\\frac\{([^}]*)\}\{([^}]*)\}/g, "($1)/($2)");
  t = t.replace(/\\sqrt\[([^\]]*)\]\{([^}]*)\}/g, "$2^(1/$1)");
  t = t.replace(/\\sqrt\{([^}]*)\}/g, "√($1)");
  t = t.replace(/\\times/g, "×").replace(/\\div/g, "÷").replace(/\\pm/g, "±");
  t = t.replace(/\\neq/g, "≠").replace(/\\leq/g, "≤").replace(/\\geq/g, "≥");
  t = t.replace(/\\approx/g, "≈").replace(/\\infty/g, "∞");
  t = t.replace(/\\pi/g, "π").replace(/\\theta/g, "θ").replace(/\\alpha/g, "α");
  t = t.replace(/\\beta/g, "β").replace(/\\gamma/g, "γ").replace(/\\delta/g, "δ");
  t = t.replace(/\\Delta/g, "Δ").replace(/\\sigma/g, "σ").replace(/\\omega/g, "ω");
  t = t.replace(/\\lambda/g, "λ").replace(/\\mu/g, "μ").replace(/\\phi/g, "φ");
  t = t.replace(/\\epsilon/g, "ε").replace(/\\therefore/g, "∴").replace(/\\perp/g, "⊥");
  t = t.replace(/\\rightarrow/g, "→").replace(/\\leftarrow/g, "←");
  t = t.replace(/\\sin/g, "sin").replace(/\\cos/g, "cos").replace(/\\tan/g, "tan");
  t = t.replace(/\\log/g, "log").replace(/\\ln/g, "ln").replace(/\\lim/g, "lim");
  t = t.replace(/\\sum_\{([^}]*)\}\^\{([^}]*)\}/g, "Σ($1 to $2)");
  t = t.replace(/\\int_\{([^}]*)\}\^\{([^}]*)\}/g, "∫($1 to $2)");
  t = t.replace(/\^\{\\circ\}/g, "°");
  t = t.replace(/\^\{([^}]*)\}/g, "^$1");
  t = t.replace(/_\{([^}]*)\}/g, "_$1");
  // Matrices
  t = t.replace(/\\begin\{pmatrix\}([\s\S]*?)\\end\{pmatrix\}/g, (_, body) => formatMatrix(body, "(", ")"));
  t = t.replace(/\\begin\{bmatrix\}([\s\S]*?)\\end\{bmatrix\}/g, (_, body) => formatMatrix(body, "[", "]"));
  t = t.replace(/\\begin\{vmatrix\}([\s\S]*?)\\end\{vmatrix\}/g, (_, body) => formatMatrix(body, "|", "|"));
  t = t.replace(/\\begin\{cases\}([\s\S]*?)\\end\{cases\}/g, (_, body) => {
    const rows = body.split("\\\\").filter((r: string) => r.trim());
    return "{ " + rows.map((r: string) => r.replace(/&/g, " ").trim()).join(", ") + " }";
  });
  t = t.replace(/\\[a-zA-Z]+/g, "");
  t = t.replace(/[{}]/g, "");
  t = t.replace(/\\\\/g, ", ");
  t = t.replace(/\s+/g, " ").trim();
  return t;
}

function formatMatrix(body: string, left: string, right: string): string {
  const rows = body.split("\\\\").filter((r: string) => r.trim());
  const formatted = rows.map((r: string) => r.split("&").map((c: string) => c.trim()).join("  "));
  return `${left} ${formatted.join(" ; ")} ${right}`;
}

export function generateNotePDF(note: NoteData): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = 0;
  let pageNum = 1;

  const addFooter = () => {
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_H - 15, PAGE_W - MARGIN, PAGE_H - 15);
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.textMuted);
    doc.text("Generated by JambOS — jambos.ng", MARGIN, PAGE_H - 10);
    doc.text(`Page ${pageNum}`, PAGE_W - MARGIN, PAGE_H - 10, { align: "right" });
  };

  const checkNewPage = (needed: number) => {
    if (y + needed > PAGE_H - 25) {
      addFooter();
      doc.addPage();
      pageNum++;
      y = 15;
    }
  };

  const drawRoundedRect = (
    x: number, yPos: number, w: number, h: number, r: number,
    fill: [number, number, number], stroke?: [number, number, number]
  ) => {
    doc.setFillColor(...fill);
    if (stroke) {
      doc.setDrawColor(...stroke);
      doc.setLineWidth(0.4);
      doc.roundedRect(x, yPos, w, h, r, r, "FD");
    } else {
      doc.roundedRect(x, yPos, w, h, r, r, "F");
    }
  };

  const wrapText = (text: string, maxWidth: number, fontSize: number): string[] => {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth) as string[];
  };

  const subject = note.subject.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

  // ═══════════════════════════════════
  // HEADER BANNER
  // ═══════════════════════════════════
  drawRoundedRect(MARGIN, 12, CONTENT_W, 40, 4, COLORS.darkGreen);

  // Brand name
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.white);
  doc.text("Jamb", MARGIN + 12, 29);
  doc.setTextColor(...COLORS.green);
  doc.text("OS", MARGIN + 12 + doc.getTextWidth("Jamb"), 29);

  // Tagline
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.textMuted);
  doc.text("AI-Powered JAMB Study Notes", MARGIN + 12, 36);

  // Subject badge
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.green);
  doc.text(subject, MARGIN + 12, 46);

  y = 60;

  // ═══════════════════════════════════
  // TITLE + META
  // ═══════════════════════════════════
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.textPrimary);
  const titleLines = wrapText(note.topicName, CONTENT_W, 18);
  titleLines.forEach((line) => {
    checkNewPage(8);
    doc.text(line, MARGIN, y);
    y += 8;
  });

  y += 1;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.textMuted);
  const meta = `Based on JAMB questions `;
  doc.text(meta, MARGIN, y);
  y += 8;

  // ═══════════════════════════════════
  // SUMMARY BOX
  // ═══════════════════════════════════
  if (note.summary) {
    const summaryText = cleanMath(note.summary);
    const summaryLines = wrapText(summaryText, CONTENT_W - 20, 10);
    const boxH = summaryLines.length * 5 + 18;

    checkNewPage(boxH + 10);

    // Label
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...COLORS.green);
    doc.text("KEY TAKEAWAY", MARGIN, y);
    y += 4;

    drawRoundedRect(MARGIN, y, CONTENT_W, boxH, 3, COLORS.greenBg, COLORS.green);

    // Green left accent bar
    doc.setFillColor(...COLORS.green);
    doc.roundedRect(MARGIN, y, 3, boxH, 1.5, 1.5, "F");

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(22, 101, 52); // dark green text
    let sY = y + 10;
    summaryLines.forEach((line) => {
      doc.text(line, MARGIN + 12, sY);
      sY += 5;
    });

    y += boxH + 6;
  }

  // ═══════════════════════════════════
  // QUICK REFERENCE BOXES
  // ═══════════════════════════════════
  const drawBox = (
    items: string[],
    label: string,
    labelColor: [number, number, number],
    bgColor: [number, number, number],
    borderColor: [number, number, number],
    iconChar: string,
  ) => {
    if (items.length === 0) return;

    // Calculate box height
    let totalH = 14;
    const itemLines: string[][] = [];
    items.forEach((item) => {
      const cleaned = cleanMath(item);
      const lines = wrapText(cleaned, CONTENT_W - 30, 9);
      itemLines.push(lines);
      totalH += lines.length * 4.5 + 4;
    });

    checkNewPage(totalH + 10);

    // Section label
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...labelColor);
    doc.text(label.toUpperCase(), MARGIN, y);
    y += 4;

    drawRoundedRect(MARGIN, y, CONTENT_W, totalH, 3, bgColor, borderColor);

    let boxY = y + 9;
    itemLines.forEach((lines) => {
      // Icon
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...labelColor);
      doc.text(iconChar, MARGIN + 8, boxY);

      // Text
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.textSecondary);
      lines.forEach((line, li) => {
        doc.text(line, MARGIN + 16, boxY + li * 4.5);
      });
      boxY += lines.length * 4.5 + 4;
    });

    y += totalH + 6;
  };

  drawBox(note.keyFormulas, "Key Formulas", COLORS.green, COLORS.greenBg, COLORS.green, "▸");
  drawBox(note.commonMistakes, "Common Mistakes", COLORS.red, COLORS.redBg, COLORS.red, "✕");
  drawBox(note.examTips, "Exam Tips", COLORS.amber, COLORS.amberBg, COLORS.amber, "★");

  // ═══════════════════════════════════
  // DIVIDER
  // ═══════════════════════════════════
  checkNewPage(10);
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  // ═══════════════════════════════════
  // MAIN CONTENT
  // ═══════════════════════════════════
  const contentLines = note.content.split("\n");

  for (const rawLine of contentLines) {
    const line = rawLine.trim();
    if (!line) {
      y += 3;
      continue;
    }

    // H2
    if (line.startsWith("## ")) {
      const heading = line.slice(3).trim();
      checkNewPage(16);
      y += 4;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COLORS.textPrimary);
      const hLines = wrapText(heading, CONTENT_W, 14);
      hLines.forEach((hl) => {
        doc.text(hl, MARGIN, y);
        y += 6.5;
      });
      // Green underline
      doc.setDrawColor(...COLORS.green);
      doc.setLineWidth(1);
      doc.line(MARGIN, y - 2, MARGIN + 40, y - 2);
      doc.setLineWidth(0.3);
      y += 4;
      continue;
    }

    // H3
    if (line.startsWith("### ")) {
      const heading = line.slice(4).trim();
      checkNewPage(12);
      y += 3;
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...COLORS.green);
      const hLines = wrapText(heading, CONTENT_W, 11);
      hLines.forEach((hl) => {
        doc.text(hl, MARGIN, y);
        y += 5.5;
      });
      y += 2;
      continue;
    }

    // Display math
    if (line.startsWith("$$") && line.endsWith("$$")) {
      const mathText = cleanLatex(line.slice(2, -2));
      checkNewPage(18);

      const mathLines = wrapText(mathText, CONTENT_W - 24, 10);
      const mathBoxH = mathLines.length * 5 + 12;

      drawRoundedRect(MARGIN + 5, y, CONTENT_W - 10, mathBoxH, 3, COLORS.bgLight, COLORS.border);

      doc.setFontSize(10);
      doc.setFont("courier", "normal");
      doc.setTextColor(...COLORS.textPrimary);
      let mY = y + 8;
      mathLines.forEach((ml) => {
        const mW = doc.getTextWidth(ml);
        doc.text(ml, MARGIN + (CONTENT_W / 2) - (mW / 2), mY);
        mY += 5;
      });

      y += mathBoxH + 4;
      continue;
    }

    // Bullet list
    if (line.startsWith("- ") || line.startsWith("* ")) {
      const itemText = cleanMath(line.slice(2).trim());
      const bLines = wrapText(itemText, CONTENT_W - 14, 9.5);
      checkNewPage(bLines.length * 4.5 + 3);

      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.textSecondary);

      // Bullet
      doc.setFillColor(...COLORS.green);
      doc.circle(MARGIN + 4, y - 1.2, 1, "F");

      bLines.forEach((bl, bi) => {
        doc.text(bl, MARGIN + 10, y + bi * 4.5);
      });
      y += bLines.length * 4.5 + 2;
      continue;
    }

    // Numbered list
    if (/^\d+\.\s/.test(line)) {
      const itemText = cleanMath(line);
      const nLines = wrapText(itemText, CONTENT_W - 10, 9.5);
      checkNewPage(nLines.length * 4.5 + 3);

      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.textSecondary);
      nLines.forEach((nl, ni) => {
        doc.text(nl, MARGIN + 6, y + ni * 4.5);
      });
      y += nLines.length * 4.5 + 2;
      continue;
    }

    // Regular paragraph
    const pText = cleanMath(line);
    if (pText) {
      const pLines = wrapText(pText, CONTENT_W, 9.5);
      checkNewPage(pLines.length * 4.5 + 2);

      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.textSecondary);
      pLines.forEach((pl, pi) => {
        doc.text(pl, MARGIN, y + pi * 4.5);
      });
      y += pLines.length * 4.5 + 2;
    }
  }

  // ═══════════════════════════════════
  // END BANNER
  // ═══════════════════════════════════
  checkNewPage(30);
  y += 6;
  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.textMuted);
  const brandW1 = doc.getTextWidth("Jamb");
  const brandW2 = doc.getTextWidth("OS");
  const totalBrandW = brandW1 + brandW2;
  doc.text("Jamb", (PAGE_W - totalBrandW) / 2, y);
  doc.setTextColor(...COLORS.green);
  doc.text("OS", (PAGE_W - totalBrandW) / 2 + brandW1, y);

  y += 5;
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.textMuted);
  doc.text("Study smarter. Score higher.", PAGE_W / 2, y, { align: "center" });
  y += 4;
  doc.text("jambos.ng", PAGE_W / 2, y, { align: "center" });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_H - 15, PAGE_W - MARGIN, PAGE_H - 15);
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.textMuted);
    doc.text("Generated by JambOS — jambos.ng", MARGIN, PAGE_H - 10);
    doc.text(`Page ${i} of ${totalPages}`, PAGE_W - MARGIN, PAGE_H - 10, { align: "right" });
  }

  // Save
  const filename = `JambOS-${note.topicName.replace(/[^a-zA-Z0-9]/g, "-")}.pdf`;
  doc.save(filename);
}