import { db } from "../src/lib/db";
async function main() {
  // Create topics
  const mathTopics = await Promise.all([
    db.topic.create({
      data: {
        subject: "MATHEMATICS",
        name: "Number and Numeration",
        slug: "math-number-numeration",
        weight: 1.2,
        sortOrder: 1,
      },
    }),
    db.topic.create({
      data: {
        subject: "MATHEMATICS",
        name: "Algebra",
        slug: "math-algebra",
        weight: 1.5,
        sortOrder: 2,
      },
    }),
    db.topic.create({
      data: {
        subject: "MATHEMATICS",
        name: "Geometry and Mensuration",
        slug: "math-geometry",
        weight: 1.0,
        sortOrder: 3,
      },
    }),
    db.topic.create({
      data: {
        subject: "MATHEMATICS",
        name: "Trigonometry",
        slug: "math-trigonometry",
        weight: 0.8,
        sortOrder: 4,
      },
    }),
    db.topic.create({
      data: {
        subject: "MATHEMATICS",
        name: "Statistics and Probability",
        slug: "math-statistics",
        weight: 1.0,
        sortOrder: 5,
      },
    }),
  ]);

  const engTopics = await Promise.all([
    db.topic.create({
      data: {
        subject: "USE_OF_ENGLISH",
        name: "Comprehension",
        slug: "eng-comprehension",
        weight: 1.5,
        sortOrder: 1,
      },
    }),
    db.topic.create({
      data: {
        subject: "USE_OF_ENGLISH",
        name: "Lexis and Structure",
        slug: "eng-lexis-structure",
        weight: 1.3,
        sortOrder: 2,
      },
    }),
    db.topic.create({
      data: {
        subject: "USE_OF_ENGLISH",
        name: "Oral English",
        slug: "eng-oral",
        weight: 1.0,
        sortOrder: 3,
      },
    }),
  ]);

  const physicsTopics = await Promise.all([
    db.topic.create({
      data: {
        subject: "PHYSICS",
        name: "Mechanics",
        slug: "physics-mechanics",
        weight: 1.5,
        sortOrder: 1,
      },
    }),
    db.topic.create({
      data: {
        subject: "PHYSICS",
        name: "Waves and Optics",
        slug: "physics-waves",
        weight: 1.0,
        sortOrder: 2,
      },
    }),
    db.topic.create({
      data: {
        subject: "PHYSICS",
        name: "Electricity and Magnetism",
        slug: "physics-electricity",
        weight: 1.2,
        sortOrder: 3,
      },
    }),
  ]);

  const chemTopics = await Promise.all([
    db.topic.create({
      data: {
        subject: "CHEMISTRY",
        name: "Atomic Structure and Bonding",
        slug: "chem-atomic-structure",
        weight: 1.3,
        sortOrder: 1,
      },
    }),
    db.topic.create({
      data: {
        subject: "CHEMISTRY",
        name: "Stoichiometry",
        slug: "chem-stoichiometry",
        weight: 1.2,
        sortOrder: 2,
      },
    }),
  ]);

  // Seed questions — Mathematics
  const mathQuestions = [
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[0].id,
      year: 2023,
      body: "Simplify 3⁴ × 3² ÷ 3⁵",
      optionA: "3",
      optionB: "9",
      optionC: "27",
      optionD: "81",
      correctOption: "A" as const,
      explanation: "Using laws of indices: 3⁴ × 3² = 3⁶. Then 3⁶ ÷ 3⁵ = 3¹ = 3.",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[0].id,
      year: 2023,
      body: "Convert 0.000375 to standard form.",
      optionA: "3.75 × 10⁻³",
      optionB: "3.75 × 10⁻⁴",
      optionC: "37.5 × 10⁻⁵",
      optionD: "0.375 × 10⁻³",
      correctOption: "B" as const,
      explanation: "Move decimal 4 places right to get 3.75, so 3.75 × 10⁻⁴.",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[1].id,
      year: 2022,
      body: "If 2x + 3 = 15, find the value of x.",
      optionA: "4",
      optionB: "5",
      optionC: "6",
      optionD: "7",
      correctOption: "C" as const,
      explanation: "2x + 3 = 15 → 2x = 12 → x = 6.",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[1].id,
      year: 2022,
      body: "Solve the equation x² - 5x + 6 = 0.",
      optionA: "x = 1, x = 6",
      optionB: "x = 2, x = 3",
      optionC: "x = -2, x = -3",
      optionD: "x = -1, x = -6",
      correctOption: "B" as const,
      explanation: "Factoring: (x - 2)(x - 3) = 0, so x = 2 or x = 3.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[1].id,
      year: 2021,
      body: "If log₁₀ 2 = 0.3010, find log₁₀ 8.",
      optionA: "0.6020",
      optionB: "0.9030",
      optionC: "2.4080",
      optionD: "1.2040",
      correctOption: "B" as const,
      explanation: "log₁₀ 8 = log₁₀ 2³ = 3 × log₁₀ 2 = 3 × 0.3010 = 0.9030.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[2].id,
      year: 2023,
      body: "Find the area of a circle with radius 7 cm. (Take π = 22/7)",
      optionA: "44 cm²",
      optionB: "154 cm²",
      optionC: "88 cm²",
      optionD: "616 cm²",
      correctOption: "B" as const,
      explanation: "A = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm².",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[2].id,
      year: 2021,
      body: "A cone has a base radius of 3 cm and height of 4 cm. Find its slant height.",
      optionA: "5 cm",
      optionB: "7 cm",
      optionC: "√7 cm",
      optionD: "25 cm",
      correctOption: "A" as const,
      explanation: "l = √(r² + h²) = √(9 + 16) = √25 = 5 cm.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[3].id,
      year: 2022,
      body: "Find the value of sin 30° + cos 60°.",
      optionA: "0",
      optionB: "½",
      optionC: "1",
      optionD: "√3",
      correctOption: "C" as const,
      explanation: "sin 30° = ½ and cos 60° = ½. So ½ + ½ = 1.",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[3].id,
      year: 2021,
      body: "In a right-angled triangle, if tan θ = 3/4, find sin θ.",
      optionA: "3/5",
      optionB: "4/5",
      optionC: "3/4",
      optionD: "5/3",
      correctOption: "A" as const,
      explanation: "If tan θ = 3/4, the hypotenuse = √(9+16) = 5. So sin θ = opposite/hypotenuse = 3/5.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[4].id,
      year: 2023,
      body: "Find the mean of 2, 5, 7, 8, 13.",
      optionA: "5",
      optionB: "7",
      optionC: "8",
      optionD: "35",
      correctOption: "B" as const,
      explanation: "Mean = (2 + 5 + 7 + 8 + 13) / 5 = 35/5 = 7.",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[4].id,
      year: 2022,
      body: "A fair die is rolled once. What is the probability of getting a number greater than 4?",
      optionA: "1/6",
      optionB: "1/3",
      optionC: "1/2",
      optionD: "2/3",
      correctOption: "B" as const,
      explanation: "Numbers greater than 4 are {5, 6}. Probability = 2/6 = 1/3.",
      difficulty: "EASY" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[1].id,
      year: 2020,
      body: "If f(x) = 2x³ - 3x² + x - 1, find f(2).",
      optionA: "5",
      optionB: "7",
      optionC: "3",
      optionD: "1",
      correctOption: "A" as const,
      explanation: "f(2) = 2(8) - 3(4) + 2 - 1 = 16 - 12 + 2 - 1 = 5.",
      difficulty: "HARD" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[4].id,
      year: 2020,
      body: "The variance of a set of data is 16. Find the standard deviation.",
      optionA: "2",
      optionB: "4",
      optionC: "8",
      optionD: "256",
      correctOption: "B" as const,
      explanation: "Standard deviation = √variance = √16 = 4.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[2].id,
      year: 2020,
      body: "The interior angle of a regular polygon is 120°. How many sides does it have?",
      optionA: "5",
      optionB: "6",
      optionC: "8",
      optionD: "10",
      correctOption: "B" as const,
      explanation: "Interior angle = (n-2)×180/n. 120n = 180n - 360 → 60n = 360 → n = 6.",
      difficulty: "HARD" as const,
    },
    {
      subject: "MATHEMATICS" as const,
      topicId: mathTopics[0].id,
      year: 2019,
      body: "Evaluate (0.25)⁻¹ × (0.5)²",
      optionA: "0.5",
      optionB: "1",
      optionC: "2",
      optionD: "4",
      correctOption: "B" as const,
      explanation: "(0.25)⁻¹ = 4 and (0.5)² = 0.25. So 4 × 0.25 = 1.",
      difficulty: "HARD" as const,
    },
  ];

  // Seed questions — English
  const engQuestions = [
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[1].id,
      year: 2023,
      body: "Choose the option that best fills the gap: The students were asked to _____ their essays before submission.",
      optionA: "revise",
      optionB: "devise",
      optionC: "reverse",
      optionD: "rehearse",
      correctOption: "A" as const,
      explanation: "'Revise' means to review and amend. Context is about improving written work before submitting.",
      difficulty: "EASY" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[1].id,
      year: 2023,
      body: "Select the option that is nearest in meaning to the underlined word: The principal gave a CONCISE speech at the assembly.",
      optionA: "lengthy",
      optionB: "brief",
      optionC: "detailed",
      optionD: "impressive",
      correctOption: "B" as const,
      explanation: "'Concise' means giving a lot of information clearly in a few words — brief.",
      difficulty: "EASY" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[1].id,
      year: 2022,
      body: "Choose the option opposite in meaning to the underlined word: His BENEVOLENT attitude won him many friends.",
      optionA: "kind",
      optionB: "cruel",
      optionC: "generous",
      optionD: "careful",
      correctOption: "B" as const,
      explanation: "'Benevolent' means well-meaning and kindly. The opposite is 'cruel'.",
      difficulty: "EASY" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[2].id,
      year: 2022,
      body: "Choose the word with the correct stress pattern: PHOTOGRAPHY",
      optionA: "PHO-to-gra-phy",
      optionB: "pho-TO-gra-phy",
      optionC: "pho-to-GRA-phy",
      optionD: "pho-to-gra-PHY",
      correctOption: "B" as const,
      explanation: "The stress falls on the second syllable: pho-TO-gra-phy.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[1].id,
      year: 2021,
      body: "Choose the option that best completes the sentence: If I _____ enough money, I would have bought the car.",
      optionA: "have",
      optionB: "has",
      optionC: "had had",
      optionD: "had",
      correctOption: "C" as const,
      explanation: "This is a third conditional (past unreal). Structure: If + past perfect, would have + past participle. 'Had had' is correct.",
      difficulty: "HARD" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[0].id,
      year: 2023,
      body: "In a comprehension passage about climate change, the author argues that deforestation is the primary cause. Which of the following best describes the author's tone?",
      optionA: "Indifferent",
      optionB: "Persuasive",
      optionC: "Humorous",
      optionD: "Sarcastic",
      correctOption: "B" as const,
      explanation: "When an author 'argues' a position, the tone is persuasive — trying to convince the reader.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[1].id,
      year: 2021,
      body: "Identify the sentence with the correct punctuation.",
      optionA: "\"Where are you going.\" she asked?",
      optionB: "\"Where are you going?\" she asked.",
      optionC: "\"Where are you going\", she asked.",
      optionD: "Where are you going? \"she asked.\"",
      correctOption: "B" as const,
      explanation: "The question mark goes inside the quotation marks, and the sentence ends with a period after 'asked'.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[2].id,
      year: 2020,
      body: "Which of the following words has the stress on the first syllable?",
      optionA: "begin",
      optionB: "record (noun)",
      optionC: "about",
      optionD: "reply",
      correctOption: "B" as const,
      explanation: "As a noun, 'record' is stressed on the first syllable: RE-cord.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[1].id,
      year: 2020,
      body: "Choose the option that best fills the gap: Neither the teacher nor the students _____ present at the meeting.",
      optionA: "was",
      optionB: "were",
      optionC: "is",
      optionD: "has been",
      correctOption: "B" as const,
      explanation: "With 'neither...nor', the verb agrees with the nearer subject ('students' — plural), so 'were' is correct.",
      difficulty: "HARD" as const,
    },
    {
      subject: "USE_OF_ENGLISH" as const,
      topicId: engTopics[0].id,
      year: 2019,
      body: "In comprehension, the phrase 'reading between the lines' means:",
      optionA: "Reading very carefully",
      optionB: "Understanding the hidden meaning",
      optionC: "Skipping some lines while reading",
      optionD: "Reading aloud",
      correctOption: "B" as const,
      explanation: "'Reading between the lines' is an idiom meaning to understand what is implied but not directly stated.",
      difficulty: "EASY" as const,
    },
  ];

  // Seed questions — Physics
  const physicsQuestions = [
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[0].id,
      year: 2023,
      body: "A car starts from rest and accelerates uniformly at 2 m/s². What is its velocity after 5 seconds?",
      optionA: "5 m/s",
      optionB: "10 m/s",
      optionC: "15 m/s",
      optionD: "20 m/s",
      correctOption: "B" as const,
      explanation: "Using v = u + at: v = 0 + (2)(5) = 10 m/s.",
      difficulty: "EASY" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[0].id,
      year: 2022,
      body: "A body of mass 5 kg is acted upon by a net force of 20 N. Find the acceleration.",
      optionA: "2 m/s²",
      optionB: "4 m/s²",
      optionC: "10 m/s²",
      optionD: "100 m/s²",
      correctOption: "B" as const,
      explanation: "From Newton's second law: a = F/m = 20/5 = 4 m/s².",
      difficulty: "EASY" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[0].id,
      year: 2021,
      body: "A ball is thrown vertically upwards with a velocity of 30 m/s. Find the maximum height reached. (g = 10 m/s²)",
      optionA: "30 m",
      optionB: "45 m",
      optionC: "60 m",
      optionD: "90 m",
      correctOption: "B" as const,
      explanation: "At max height, v = 0. Using v² = u² - 2gh: 0 = 900 - 20h → h = 45 m.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[1].id,
      year: 2023,
      body: "The speed of light in vacuum is 3 × 10⁸ m/s. Find the wavelength of a wave with frequency 6 × 10¹⁴ Hz.",
      optionA: "5 × 10⁻⁷ m",
      optionB: "2 × 10⁻⁶ m",
      optionC: "5 × 10⁶ m",
      optionD: "2 × 10²² m",
      correctOption: "A" as const,
      explanation: "λ = c/f = (3 × 10⁸)/(6 × 10¹⁴) = 5 × 10⁻⁷ m.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[1].id,
      year: 2022,
      body: "Which of the following is NOT a property of sound waves?",
      optionA: "Reflection",
      optionB: "Refraction",
      optionC: "Polarization",
      optionD: "Diffraction",
      correctOption: "C" as const,
      explanation: "Sound waves are longitudinal and cannot be polarized. Polarization is a property of transverse waves only.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[2].id,
      year: 2023,
      body: "Three resistors of 2Ω, 3Ω, and 6Ω are connected in parallel. Find the effective resistance.",
      optionA: "1 Ω",
      optionB: "2 Ω",
      optionC: "6 Ω",
      optionD: "11 Ω",
      correctOption: "A" as const,
      explanation: "1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1. So R = 1 Ω.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[2].id,
      year: 2021,
      body: "An electric heater rated 1000 W is used for 2 hours. Calculate the energy consumed in kWh.",
      optionA: "0.5 kWh",
      optionB: "1 kWh",
      optionC: "2 kWh",
      optionD: "2000 kWh",
      correctOption: "C" as const,
      explanation: "Energy = Power × Time = 1 kW × 2 h = 2 kWh.",
      difficulty: "EASY" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[0].id,
      year: 2020,
      body: "The work done in pushing a box with a force of 50 N through a distance of 8 m along the direction of force is:",
      optionA: "6.25 J",
      optionB: "58 J",
      optionC: "400 J",
      optionD: "800 J",
      correctOption: "C" as const,
      explanation: "Work = Force × Distance = 50 × 8 = 400 J.",
      difficulty: "EASY" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[0].id,
      year: 2019,
      body: "A satellite moves in a circular orbit around the Earth. The centripetal force is provided by:",
      optionA: "The satellite's engine thrust",
      optionB: "Atmospheric drag",
      optionC: "Gravitational attraction",
      optionD: "Magnetic force",
      correctOption: "C" as const,
      explanation: "For a satellite in orbit, gravity provides the centripetal force needed for circular motion.",
      difficulty: "MEDIUM" as const,
    },
    {
      subject: "PHYSICS" as const,
      topicId: physicsTopics[2].id,
      year: 2019,
      body: "A charge of 5 C flows through a conductor in 2 seconds. Calculate the current.",
      optionA: "0.4 A",
      optionB: "2.5 A",
      optionC: "7 A",
      optionD: "10 A",
      correctOption: "B" as const,
      explanation: "I = Q/t = 5/2 = 2.5 A.",
      difficulty: "EASY" as const,
    },
  ];

  // Seed questions — Chemistry
  const chemQuestions = [
    {
      subject: "CHEMISTRY" as const,
      topicId: chemTopics[0].id,
      year: 2023,
      body: "What is the electronic configuration of sodium (Na, atomic number 11)?",
      optionA: "2, 8, 2",
      optionB: "2, 8, 1",
      optionC: "2, 9",
      optionD: "2, 8, 3",
      correctOption: "B" as const,
      explanation: "Sodium has 11 electrons distributed as 2, 8, 1.",
      difficulty: "EASY" as const,
    },
    {
      subject: "CHEMISTRY" as const,
      topicId: chemTopics[0].id,
      year: 2022,
      body: "Which type of bond is formed between sodium and chlorine?",
      optionA: "Covalent bond",
      optionB: "Metallic bond",
      optionC: "Ionic bond",
      optionD: "Van der Waals",
      correctOption: "C" as const,
      explanation: "Sodium (metal) transfers an electron to chlorine (non-metal), forming an ionic bond.",
      difficulty: "EASY" as const,
    },
    {
      subject: "CHEMISTRY" as const,
      topicId: chemTopics[1].id,
      year: 2023,
      body: "What volume of CO₂ (at STP) is produced when 10 g of CaCO₃ is completely decomposed? (Ca=40, C=12, O=16, molar volume = 22.4 dm³)",
      optionA: "1.12 dm³",
      optionB: "2.24 dm³",
      optionC: "11.2 dm³",
      optionD: "22.4 dm³",
      correctOption: "B" as const,
      explanation: "Molar mass of CaCO₃ = 100. Moles = 10/100 = 0.1 mol. 1 mol CaCO₃ gives 1 mol CO₂. Volume = 0.1 × 22.4 = 2.24 dm³.",
      difficulty: "HARD" as const,
    },
    {
      subject: "CHEMISTRY" as const,
      topicId: chemTopics[1].id,
      year: 2022,
      body: "How many moles of water are in 36 g of H₂O? (H=1, O=16)",
      optionA: "1",
      optionB: "2",
      optionC: "18",
      optionD: "36",
      correctOption: "B" as const,
      explanation: "Molar mass of H₂O = 18 g/mol. Moles = 36/18 = 2 moles.",
      difficulty: "EASY" as const,
    },
    {
      subject: "CHEMISTRY" as const,
      topicId: chemTopics[0].id,
      year: 2021,
      body: "An atom of element X has 17 protons. Which group and period does it belong to in the periodic table?",
      optionA: "Group 7, Period 3",
      optionB: "Group 1, Period 3",
      optionC: "Group 7, Period 2",
      optionD: "Group 3, Period 7",
      correctOption: "A" as const,
      explanation: "17 electrons: 2, 8, 7. The 7 outer electrons put it in Group 7. Three shells mean Period 3. This is Chlorine.",
      difficulty: "MEDIUM" as const,
    },
  ];

  // Insert all questions
  const allQuestions = [
    ...mathQuestions,
    ...engQuestions,
    ...physicsQuestions,
    ...chemQuestions,
  ];

  for (const q of allQuestions) {
    await db.question.create({ data: q });
  }

  console.log(`Seeded ${allQuestions.length} questions across 4 subjects`);
  console.log(
    `Topics: ${mathTopics.length} Math, ${engTopics.length} English, ${physicsTopics.length} Physics, ${chemTopics.length} Chemistry`
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });